/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mobius.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          scale={[0.2, 12, 1]}
        >
          <meshStandardMaterial attach='material' color='red' />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/mobius.glb')
