/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const mobius = useRef(null)
  const { nodes, materials } = useGLTF('/mobius.glb')

  useFrame(() => (mobius.current.rotation.x = mobius.current.rotation.y += 0.01))

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh ref={mobius}
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          scale={[0.2, 12, 1]}
        >
          <meshStandardMaterial attach='material' color='red' />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/mobius.glb')
